### ISSUE TITLE
Not available in graalvm-jdk-21

### ISSUE THREAD

**Issue by GeTOUO** [simdjson/simdjson-java#34]
https://www.graalvm.org/release-notes/JDK_21/

> - The following JDK 21 features are not available:
    - [JEP 442](https://openjdk.org/jeps/442) Foreign Function & Memory API (Third Preview)
    - [JEP 448](https://openjdk.org/jeps/448) Vector API (Sixth Incubator)

**Comment by GeTOUO** [comment]
```
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/incubator/vector/ByteVector
	at org.simdjson.StructuralIndexer.<clinit>(StructuralIndexer.java:17)
	at org.simdjson.StringParser.<clinit>(StringParser.java:13)
	at org.simdjson.TapeBuilder.<init>(TapeBuilder.java:35)
	at org.simdjson.JsonIterator.<init>(JsonIterator.java:23)
	at org.simdjson.SimdJsonParser.<init>(SimdJsonParser.java:22)
	at org.simdjson.SimdJsonParser.<init>(SimdJsonParser.java:17)
	at com.getouo.simdjsonjavatest.SimdJsonTest.main(SimdJsonTest.java:24)
Caused by: java.lang.ClassNotFoundException: jdk.incubator.vector.ByteVector
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 7 more
```

**Comment by piotrrzysko** [comment]
This library extensively uses the Vector API provided by Java, so I'm not sure what we can do about the fact that it is not available in GraalVM.

**Comment by ZhaiMo15** [comment]
I don't think [JEP 448](https://openjdk.org/jeps/448) Vector API (Sixth Incubator) is needed, [JEP 417](https://openjdk.org/jeps/417) is usable.
Are you using maven? Due to [JEP403](https://openjdk.org/jeps/403), I believe you need to add `--add-modules=jdk.incubator.vector` in your pom.

**Comment by GeTOUO** [comment]
> --add-modules=jdk.incubator.vector

Yes, I use maven to build the project, which is available after adding `--add-modules=jdk.incubator.vector` . 
Thank you.

**Comment by piotrrzysko** [comment]
Thanks @ZhaiMo15 for your help. @GeTOUO can we close this issue?

**Comment by GeTOUO** [comment]
Yes, my problem has been solved, also thanks to the author @piotrrzysko for providing this library.
